name: EsteiraCICD
on:
    push:
        branches:
            - master
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: |
                  npm install
            - name: Run tests
              run: |
                  npm run test
    build-android:
        needs: run-tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: |
                  npm install
            - name: Enablew gradlew commands
              run: |
                  cd android && chmod +x ./gradlew
            - name: Build Android Debug
              run: |
                  cd android && ./gradlew assembleDebug
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: app-debug.apk
                  path: android/app/build/outputs/apk/debug/
